#!/usr/bin/python3

import sys
import json
import os
import argparse
import string

USED_BUILD_ARGS = {
    'openveo-db': ['ADMIN_OPERATOR_PASSWD', 'OPENVEO_OPERATOR_PASSWD', 'OPENVEO_USER_PASSWD']
    }


class ArgumentParser(argparse.ArgumentParser):
    ACTIONS = 'build', 'nop'

    def __init__(self):
        argparse.ArgumentParser.__init__(self)
        self.add_argument("-c", "--config", default=None, type=str)
        self.add_argument(dest="action", nargs=1, type=str, choices=self.ACTIONS, default=None)
        self.add_argument(dest="images", nargs='*', type=str, metavar='IMG')

    def parse_args(self, argv):
        args = argparse.ArgumentParser.parse_args(self, argv)
        return args
        # print(args)
        # setattr(args, 'action', None)
        # for a in self.ACTIONS:
        #     if getattr(args, a):
        #         setattr(args, 'action', a)
        #         break
        # return args


class Application:
    def __init__(self, argv):
        self._argv = argv
        self._argparser = ArgumentParser()
        self._config = None

    def getRootDir(self):
        return os.path.abspath("%s/../.." % __file__)

    def makeBuildArgs(self, image):
        build_args = {}

        try:
            used_build_args = USED_BUILD_ARGS[image]
        except KeyError:
            used_build_args = []

        for a in used_build_args:
            build_args[a] = self._config['build_args'][a]
#        build_args['HOSTNAME_SUFFIX'] = image[len('openveo-'):]

        cmd = []
        for k,v in build_args.items():
            cmd += ['--build-arg %s="%s"' % (k,v)]
        cmd = ' '.join(cmd)
        return cmd

    def loadConfig(self, args):
        if args.config==None:
            fn = "%s/config-example.json" % self.getRootDir()
        else:
            fn = args.config
        self._config = json.loads(open(fn).read())

    def __call__(self):
        args = self._argparser.parse_args(self._argv)
        print(args)
        self.loadConfig(args)
        action = args.action[0]
        try:
            f = getattr(self, "do%s%s" % (action[0].upper(), action[1:].lower()))
        except:
            f = self.printHelp
        f(args)

    def printHelp(self, args):
        self._argparser.print_help()

    def system(self, cmd):
        print("* %s" % cmd)
        sts = os.system(cmd)
        if cmd != 0:
            sys.exit(-1)

    def doBuild(self, args):
        for img in args.images:
            cmd = "docker build "
            cmd += self.makeBuildArgs(img)
            cmd += " -t %s %s" % (img,img)
            self.system(cmd)

    def doNop(self, args):
        print('Nop !')


def main():
    app = Application(sys.argv[1:])
    app()


if __name__ == '__main__':
    main()
